### PR TITLE
CoffeeTurtle

### PR DESCRIPTION
**Pull request by syntagmatic**
It is what it is.

``` coffeescript
turtle (t) ->
  [200, 400, 100].map (a) ->
    (t) -> ~~((Math.sin(t/a) * 1800) / 50) * 8

```

### CODE REVIEW

**Comment by syntagmatic** [comment]
``` coffeescript
quads = [0, -90, 90, 180, -180]

fortor = (a) ->
  n = ~~(Math.random() * 400)
  (t) ->
    if (t % n) then a else quads.map(fortor)

turtle (t) ->
  [fortor(0)]
```

**Comment by tmcw** [comment]
Awesome, want to use the [coffeescript mode](https://github.com/tmcw/turtle/tree/gh-pages/v1/codemirror-3.16/mode/coffeescript) too?

**Comment by syntagmatic** [comment]
regex
Coffeescript mode thinks that's a regex.

I improved Coffeescript mode a while back, but never it merged in. Maybe I'll clean it up and try again.
http://fleetinbeing.net/beans/

**Comment by tmcw** [comment]
Hm, bummer. Will merge for now and survey how tributary and co do cs highlighting.

**Pull request merged**
